name: validate
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
      - bob/*
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt -q update
          sudo apt -q install libseccomp-dev
      - uses: golangci/golangci-lint-action@v2
        with:
          # must be specified without patch version
          version: v1.40

  shfmt:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: vars
      run: |
        echo "VERSION=3.2.4" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: cache go mod and $GOCACHE
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-shfmt-${{ env.VERSION }}
        restore-keys: ${{ runner.os }}-shfmt-
    - name: install shfmt
      run: |
        command -v shfmt || \
          (cd ~ && GO111MODULE=on time go get mvdan.cc/sh/v3/cmd/shfmt@v$VERSION)
    - name: shfmt
      run: make shfmt

  shellcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: vars
        run: |
          echo 'VERSION=v0.7.2' >> $GITHUB_ENV
          echo 'BASEURL=https://github.com/koalaman/shellcheck/releases/download' >> $GITHUB_ENV
          echo 'SHA256SUM=12ee2e0b90a3d1e9cae24ac9b2838be66b48573cb2c8e8f3c566b959df6f050c' >> $GITHUB_ENV
          echo ~/bin >> $GITHUB_PATH
      - name: install shellcheck
        run: |
          mkdir ~/bin
          curl -sSfL --retry 5 $BASEURL/$VERSION/shellcheck-$VERSION.linux.x86_64.tar.xz |
            tar xfJ - -C ~/bin --strip 1 shellcheck-$VERSION/shellcheck
          sha256sum ~/bin/shellcheck | grep -q $SHA256SUM
          # make sure to remove the old version
          sudo rm -f /usr/bin/shellcheck
      - uses: lumaxis/shellcheck-problem-matchers@v1
      - name: shellcheck
        run: |
          make shellcheck

  deps:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: cache go mod and $GOCACHE
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go.sum-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go.sum-
    - name: verify deps
      run: make verify-dependencies


  commit:
    runs-on: ubuntu-20.04
    # Only check commits on pull requests.
    if: github.event_name == 'pull_request'
    steps:
      - name: get pr commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: check subject line length
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^.{0,72}(\n.*)*$'
          error: 'Subject too long (max 72)'


  cross:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      # We have to run this under Docker as Ubuntu (host) does not support all
      # the architectures we want to compile test against, and Dockerfile uses
      # Debian (which does).
      #
      # XXX: as currently this is the only job that is using Docker, we are
      # building and using the runcimage locally. In case more jobs running
      # under Docker will emerge, it will be good to have a separate make
      # runcimage job and share its result (the docker image) with whoever
      # needs it.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: build docker image
      run: make runcimage
    - name: cross
      run: make cross


  cfmt:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: |
        sudo apt -qq update
        sudo apt -qq install indent
    - name: cfmt
      run: |
        make cfmt
        git diff --exit-code


  build-release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: |
        sudo apt -qq update
        sudo apt -qq install gperf

    - name: install arm deps
      if: matrix.arch == 'arm64'
      run: |
        sudo apt install gcc-aarch64-linux-gnu
        echo CC=aarch64-linux-gnu-gcc >> $GITHUB_ENV
        echo CC_FOR_TARGET=aarch64-linux-gnu-gcc >> $GITHUB_ENV
        echo STRIP=aarch64-linux-gnu-strip >> $GITHUB_ENV
    - name: make release
      env:
        GOARCH: ${{ matrix.arch }}
      run: make release
    - name: install deps
      run: |
        ls -llah release/*
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ github.run_id }}
        path: release/*

  release:
    name: Create containerd Release
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: [build-release]
    outputs:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Download builds and release notes
        uses: actions/download-artifact@v2
        with:
          path: release/*
          name: release-${{ github.run_id }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Runc ${{ needs.check.outputs.stringver }}
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
  artifact-discovery:
    name: Discover the release artifact
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: [release]
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: DL build artifact
        uses: actions/download-artifact@v2
        with:
          path: release/*
          name: release-${{ github.run_id }}
      - name: Catalog build assets for upload
        id: catalog
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          ls -l . || true
          ls / || true
          find release || true
          PREFIX=("release/${{ matrix.arch }}")
          ARTIFACT=()
          for f in `find ${PREFIX}  -mindepth 1 -maxdepth 1 -printf '%f\n'`; do
            ARTIFACT+=($f)
          done
          jq --null-input -rc \
             --arg ARTIFACT $ARTIFACT \
             --arg PREFIX $PREFIX \
             '{
                "artifact": [$ARTIFACT],
             } | {artifacts: [.artifact[] | {name: .,prefix: $PREFIX}]}' > manager/artifacts.${{ matrix.arch }}.json || true

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: manager-${{ github.run_id }}
          path: manager/*
  release-upload:
    name: Upload containerd tarballs
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: [release]

    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
     - name: Download builds and release notes
       uses: actions/download-artifact@v2
       with:
         path: builds
     - name: Catalog build assets for upload
       id: catalog
       env:
         ARCH: ${{ matrix.arch }}
       run: |
         _filenum=1
         for f in `ls "release/"`; do
           echo "::set-output name=file${_filenum}::${f}"
           let "_filenum+=1"
         done
     - name: Upload containerd tarball
       uses: actions/upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ needs.release.outputs.upload_url }}
         asset_path: ./release/${{ matrix.arch }}/${{ steps.catalog.outputs.file1 }}
         asset_name: ${{ steps.catalog.outputs.file1 }}
         asset_content_type: application/gzip

#      - name: Upload sha256 sum
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: ./builds/containerd-binaries-${{ matrix.os }}-${{ matrix.arch }}/${{ steps.catalog.outputs.file2 }}
#          asset_name: ${{ steps.catalog.outputs.file2 }}
#          asset_content_type: text/plain
#      - name: Upload cri containerd tarball
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: ./builds/cri-containerd-binaries-${{ matrix.os }}-${{ matrix.arch }}/${{ steps.catalog.outputs.file3 }}
#          asset_name: ${{ steps.catalog.outputs.file3 }}
#          asset_content_type: application/gzip
#      - name: Upload cri sha256 sum
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: ./builds/cri-containerd-binaries-${{ matrix.os }}-${{ matrix.arch }}/${{ steps.catalog.outputs.file4 }}
#          asset_name: ${{ steps.catalog.outputs.file4 }}
#          asset_content_type: text/plain
#      - name: Upload cri/cni containerd tarball
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: ./builds/cri-containerd-binaries-${{ matrix.os }}-${{ matrix.arch }}/${{ steps.catalog.outputs.file5 }}
#          asset_name: ${{ steps.catalog.outputs.file5 }}
#          asset_content_type: application/gzip
#      - name: Upload cri/cni sha256 sum
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: ./builds/cri-containerd-binaries-${{ matrix.os }}-${{ matrix.arch }}/${{ steps.catalog.outputs.file6 }}
#          asset_name: ${{ steps.catalog.outputs.file6 }}
#          asset_content_type: text/plain
